name: Automated Test for the Project Automated Data Pipeline

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  project-data-pipeline-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
        
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "./main/project/requirements.txt"

    # Run exercise feedback
    - name: Automated Test for the Project Automated Data Pipeline
      run: |
        ./main/project/tests.sh
